### ISSUE TITLE
[BUG] Erro na rota login/forgotPassword

### ISSUE THREAD

**Issue by Jaquelaurenti** [codenation-dev/squad-3-ad-csharp-women-itau-1#26]
Erro ao acessar a rota de forgotPassword.
![image](https://user-images.githubusercontent.com/39747516/81188853-4429b980-8f8c-11ea-848c-6374a654ae2e.png)

**Comment by iprih** [comment]
Bug corrigido.
Aguardando confimação para encerrar issue.

**Comment by Jaquelaurenti** [comment]
@iprih  pode fechar, tá funcionando já!
