### ISSUE TITLE
Criar Controller, DTO, Model e Service de  Level

### ISSUE THREAD

**Issue by Jaquelaurenti** [codenation-dev/squad-3-ad-csharp-women-itau-1#3]
Criar com base no Mer abaixo:

![image](https://user-images.githubusercontent.com/39747516/79513012-2d411880-8019-11ea-8f83-9cdaf277d4a1.png)

Critérios de Aceite:
1- CRUD criado
2- CRUD funcionando em todas as rotas no swagger.
3- Id do Level com autoincrement

**Comment by iprih** [comment]
Autoincrement e POST criados e testados
