### ISSUE TITLE
Criar Controller, DTO, Model e Service de ErrorOcurrence

### ISSUE THREAD

**Issue by Jaquelaurenti** [codenation-dev/squad-3-ad-csharp-women-itau-1#6]
Criar com base no MER abaixo
![image](https://user-images.githubusercontent.com/39747516/79517626-1e606300-8025-11ea-9f8a-b2f7d976f0d7.png)

Critérios de Aceite:
1- CRUD criado
2- CRUD funcionando em todas as rotas no swagger.
3- Id da Ocurrence com autoincrement

**Comment by julianeventura** [comment]
Foi adicionado o campo Origin (origem) na entidade ErrorOcurrence

**Comment by Jaquelaurenti** [comment]
Feitos alguns ajustes na Model da ErrorOcurrence, conforme commit: 
https://github.com/codenation-dev/squad-3-ad-csharp-women-itau-1/commit/9c4a176c9e1717e292c8ae6bf32fe9736c051263

**Comment by Jaquelaurenti** [comment]
Capturando o IP de quem está inserindo o POST através da solucao abaixo, add no Origin

Criar o metodo de IP do Usuario conforme esse stack:
https://pt.stackoverflow.com/questions/84241/capturar-ip-real-do-usu%C3%A1rio
